/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/reviews/$slug',
  path: '/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guides/$slug' | '/reviews/$slug' | '/guides/' | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guides/$slug' | '/reviews/$slug' | '/guides' | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/guides/$slug'
    | '/reviews/$slug'
    | '/guides/'
    | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/reviews/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ReviewsSlugRoute: ReviewsSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
