/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyTrustUsRouteImport } from './routes/why-trust-us'
import { Route as TrustScoreRouteImport } from './routes/trust-score'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowWeTestRouteImport } from './routes/how-we-test'
import { Route as DisclaimersRouteImport } from './routes/disclaimers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases.index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VsMatchupRouteImport } from './routes/vs.$matchup'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases.$slug'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as GoSlugRouteImport } from './routes/go.$slug'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BestSlugRouteImport } from './routes/best.$slug'
import { Route as CountriesSlugCitiesCityRouteImport } from './routes/countries.$slug.cities.$city'

const WhyTrustUsRoute = WhyTrustUsRouteImport.update({
  id: '/why-trust-us',
  path: '/why-trust-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustScoreRoute = TrustScoreRouteImport.update({
  id: '/trust-score',
  path: '/trust-score',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeTestRoute = HowWeTestRouteImport.update({
  id: '/how-we-test',
  path: '/how-we-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimersRoute = DisclaimersRouteImport.update({
  id: '/disclaimers',
  path: '/disclaimers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsMatchupRoute = VsMatchupRouteImport.update({
  id: '/vs/$matchup',
  path: '/vs/$matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/reviews/$slug',
  path: '/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSlugRoute = BestSlugRouteImport.update({
  id: '/best/$slug',
  path: '/best/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugCitiesCityRoute = CountriesSlugCitiesCityRouteImport.update({
  id: '/cities/$city',
  path: '/cities/$city',
  getParentRoute: () => CountriesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/disclaimers': typeof DisclaimersRoute
  '/how-we-test': typeof HowWeTestRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/trust-score': typeof TrustScoreRoute
  '/why-trust-us': typeof WhyTrustUsRoute
  '/best/$slug': typeof BestSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$slug': typeof CountriesSlugRouteWithChildren
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/vs/$matchup': typeof VsMatchupRoute
  '/blog/': typeof BlogIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/countries/$slug/cities/$city': typeof CountriesSlugCitiesCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/disclaimers': typeof DisclaimersRoute
  '/how-we-test': typeof HowWeTestRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/trust-score': typeof TrustScoreRoute
  '/why-trust-us': typeof WhyTrustUsRoute
  '/best/$slug': typeof BestSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$slug': typeof CountriesSlugRouteWithChildren
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/vs/$matchup': typeof VsMatchupRoute
  '/blog': typeof BlogIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/countries/$slug/cities/$city': typeof CountriesSlugCitiesCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/disclaimers': typeof DisclaimersRoute
  '/how-we-test': typeof HowWeTestRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/trust-score': typeof TrustScoreRoute
  '/why-trust-us': typeof WhyTrustUsRoute
  '/best/$slug': typeof BestSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$slug': typeof CountriesSlugRouteWithChildren
  '/go/$slug': typeof GoSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/vs/$matchup': typeof VsMatchupRoute
  '/blog/': typeof BlogIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/countries/$slug/cities/$city': typeof CountriesSlugCitiesCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compare'
    | '/contact'
    | '/disclaimers'
    | '/how-we-test'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/trust-score'
    | '/why-trust-us'
    | '/best/$slug'
    | '/blog/$slug'
    | '/countries/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/reviews/$slug'
    | '/team/$slug'
    | '/use-cases/$slug'
    | '/vs/$matchup'
    | '/blog/'
    | '/countries/'
    | '/guides/'
    | '/reviews/'
    | '/use-cases/'
    | '/countries/$slug/cities/$city'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compare'
    | '/contact'
    | '/disclaimers'
    | '/how-we-test'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/trust-score'
    | '/why-trust-us'
    | '/best/$slug'
    | '/blog/$slug'
    | '/countries/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/reviews/$slug'
    | '/team/$slug'
    | '/use-cases/$slug'
    | '/vs/$matchup'
    | '/blog'
    | '/countries'
    | '/guides'
    | '/reviews'
    | '/use-cases'
    | '/countries/$slug/cities/$city'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compare'
    | '/contact'
    | '/disclaimers'
    | '/how-we-test'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/trust-score'
    | '/why-trust-us'
    | '/best/$slug'
    | '/blog/$slug'
    | '/countries/$slug'
    | '/go/$slug'
    | '/guides/$slug'
    | '/reviews/$slug'
    | '/team/$slug'
    | '/use-cases/$slug'
    | '/vs/$matchup'
    | '/blog/'
    | '/countries/'
    | '/guides/'
    | '/reviews/'
    | '/use-cases/'
    | '/countries/$slug/cities/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DisclaimersRoute: typeof DisclaimersRoute
  HowWeTestRoute: typeof HowWeTestRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  TrustScoreRoute: typeof TrustScoreRoute
  WhyTrustUsRoute: typeof WhyTrustUsRoute
  BestSlugRoute: typeof BestSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CountriesSlugRoute: typeof CountriesSlugRouteWithChildren
  GoSlugRoute: typeof GoSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  TeamSlugRoute: typeof TeamSlugRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  VsMatchupRoute: typeof VsMatchupRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-trust-us': {
      id: '/why-trust-us'
      path: '/why-trust-us'
      fullPath: '/why-trust-us'
      preLoaderRoute: typeof WhyTrustUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-score': {
      id: '/trust-score'
      path: '/trust-score'
      fullPath: '/trust-score'
      preLoaderRoute: typeof TrustScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-test': {
      id: '/how-we-test'
      path: '/how-we-test'
      fullPath: '/how-we-test'
      preLoaderRoute: typeof HowWeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimers': {
      id: '/disclaimers'
      path: '/disclaimers'
      fullPath: '/disclaimers'
      preLoaderRoute: typeof DisclaimersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$matchup': {
      id: '/vs/$matchup'
      path: '/vs/$matchup'
      fullPath: '/vs/$matchup'
      preLoaderRoute: typeof VsMatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/reviews/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best/$slug': {
      id: '/best/$slug'
      path: '/best/$slug'
      fullPath: '/best/$slug'
      preLoaderRoute: typeof BestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug/cities/$city': {
      id: '/countries/$slug/cities/$city'
      path: '/cities/$city'
      fullPath: '/countries/$slug/cities/$city'
      preLoaderRoute: typeof CountriesSlugCitiesCityRouteImport
      parentRoute: typeof CountriesSlugRoute
    }
  }
}

interface CountriesSlugRouteChildren {
  CountriesSlugCitiesCityRoute: typeof CountriesSlugCitiesCityRoute
}

const CountriesSlugRouteChildren: CountriesSlugRouteChildren = {
  CountriesSlugCitiesCityRoute: CountriesSlugCitiesCityRoute,
}

const CountriesSlugRouteWithChildren = CountriesSlugRoute._addFileChildren(
  CountriesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DisclaimersRoute: DisclaimersRoute,
  HowWeTestRoute: HowWeTestRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  TrustScoreRoute: TrustScoreRoute,
  WhyTrustUsRoute: WhyTrustUsRoute,
  BestSlugRoute: BestSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CountriesSlugRoute: CountriesSlugRouteWithChildren,
  GoSlugRoute: GoSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ReviewsSlugRoute: ReviewsSlugRoute,
  TeamSlugRoute: TeamSlugRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  VsMatchupRoute: VsMatchupRoute,
  BlogIndexRoute: BlogIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
